name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-command: 'npm run "build linux"'
            output: 'AppImage & snap'
          - os: ubuntu-latest
            build-command: 'npm run "build linux deb"'
            output: 'deb'
          - os: ubuntu-latest
            build-command: 'npm run "build linux freebsd"'
            output: 'freebsd'
          - os: ubuntu-latest
            build-command: 'npm run "build linux rpm"'
            output: 'rpm'
          - os: windows-latest
            build-command: 'npm run "build windows"'
            output: 'exe'
          - os: windows-latest
            build-command: 'npm run "build windows msi"'
            output: 'msi'
          - os: macos-latest
            build-command: 'npm run "build mac"'
            output: 'dmg'
            
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - run: npm ci
    - name: Build
      run: ${{ matrix.build-command }}
    - uses: actions/upload-artifact@v4
      with:
        name: WLED-${{ matrix.os }}-${{ matrix.output }}
        path: |
          dist/WLED-*.AppImage
          dist/WLED-*.deb
          dist/WLED-*.rpm
          dist/WLED-*.snap
          dist/WLED-*.freebsd
          dist/WLED-*.dmg
          dist/WLED-*.msi
          dist/WLED-*.exe
          
